# Generated by Django 3.2.3 on 2021-05-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('creator', models.CharField(max_length=60, verbose_name='Создатель')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('date_start', models.DateField(blank=True, verbose_name='Дата начала подработки')),
                ('date_finish', models.DateField(blank=True, verbose_name='Дата окончания подработки')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подработка',
                'verbose_name_plural': 'Подработки',
                'ordering': ('title', 'creator'),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=80, verbose_name='Имя')),
                ('department_code', models.CharField(max_length=80, verbose_name='Код подразделения')),
                ('post', models.CharField(max_length=80, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ('lastname', 'firstname'),
            },
        ),
    ]
