# Generated by Django 3.2.3 on 2021-05-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='division_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='division_code_gosb',
            field=models.CharField(choices=[('4157', '4157'), ('9070', '9070'), ('8635', '8635'), ('8636', '8636'), ('8567', '8567'), ('8645', '8645'), ('8557', '8557'), ('8556', '8556')], default='', max_length=400, verbose_name='ГОСБ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='division_code_vsp',
            field=models.CharField(default='', max_length=400, verbose_name='ВСП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.TextField(choices=[('СМО', 'Старший менеджер по обслуживанию'), ('ВМО', 'Ведущий менеджер по обслуживанию'), ('МО', 'Менеджер по обслуживанию'), ('СКМ', 'Старший клиентский менеджер'), ('КМ', 'Клиентский менеджер'), ('К', 'Консультант')], verbose_name='Должность'),
        ),
    ]
