# Generated by Django 3.2.3 on 2021-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210523_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_str',
            field=models.CharField(default='', max_length=50, verbose_name='Пароль в текстовом виде (для разработки)'),
            preserve_default=False,
        ),
    ]
